### ISSUE TITLE
Internal Server Error when using Litestar with enabled session authentication 

### ISSUE THREAD

**Issue by varuzam** [peterschutt/sqladmin-litestar-plugin#12]
Hello.
When session authentication is enabled in Litestar  the requests to /admin return http error 500. traceback is attached.
[error.txt](https://github.com/user-attachments/files/15525868/error.txt)

**Comment by peterschutt** [comment]
Thanks - I had a hunch there might be some issues around this.

Can you create a MCVE so I can reproduce please?

**Comment by peterschutt** [comment]
Sorry about the delay on this @varuzam.

In the end the fix was quite trivial, by passing the starlette application a copy of the scope object, it prevents any litestar components that have already taken a reference to it from being impacted by any changes that starlette makes to it.

Cheers for the report and MCVE!
